# kmotor_kicad.py
# KiCad renderer only for KMotor_Pro
# Generated during Phase 1 refactoring

import math
import pcbnew


def as_point(x, y, fpoint):
    """Convert coordinates to KiCad point."""
    return fpoint(int(round(x)), int(round(y)))


def item_token(item):
    """Get unique token for KiCad item."""
    for getter in ("GetUuid", "GetKIID"):
        if hasattr(item, getter):
            try:
                kiid = getattr(item, getter)()
                if hasattr(kiid, "AsString"):
                    return kiid.AsString()
                return str(kiid)
            except Exception:
                pass
    if hasattr(item, "m_Uuid"):
        try:
            return item.m_Uuid.AsString()
        except Exception:
            pass
    return str(id(item))


def tag_generated_zone(zone, kind, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
    """Tag zone as generated."""
    priority = GENERATED_ZONE_PRIORITIES[kind]
    try:
        zone.SetAssignedPriority(priority)
    except Exception:
        pass
    zone_name = GENERATED_ZONE_NAME_PREFIX + kind
    for setter in ("SetZoneName", "SetName"):
        if hasattr(zone, setter):
            try:
                getattr(zone, setter)(zone_name)
                break
            except Exception:
                pass
    generated_zone_tokens.add(item_token(zone))


def is_generated_zone(zone, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
    """Check if zone was generated by KMotor."""
    token = item_token(zone)
    if token in generated_zone_tokens:
        return True
    for getter in ("GetZoneName", "GetName"):
        if hasattr(zone, getter):
            try:
                name = getattr(zone, getter)()
                if name and str(name).startswith(GENERATED_ZONE_NAME_PREFIX):
                    return True
            except Exception:
                pass
    if hasattr(zone, "GetAssignedPriority"):
        try:
            return zone.GetAssignedPriority() in GENERATED_ZONE_PRIORITIES.values()
        except Exception:
            pass
    return False


def cleanup_generated_zones(board, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
    """Remove all generated zones from board."""
    zones_to_remove = []
    for zone in board.Zones():
        if is_generated_zone(zone, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
            zones_to_remove.append(zone)
    for zone in zones_to_remove:
        board.Remove(zone)


def eda_angle(angle, KICAD_VERSION):
    """Convert angle to KiCad EDA format."""
    if KICAD_VERSION < 7:
        return angle * 180 / math.pi * 100
    else:
        return pcbnew.EDA_ANGLE(angle, pcbnew.RADIANS_T)


def add_silk_segment(board, start_xy, end_xy, fpoint, SCALE, width=None, clip_to_outline=False, clip_margin=0.0, bounds=None):
    """Add silkscreen segment."""
    if clip_to_outline and bounds:
        from .kmotor_geometry import clip_segment_to_outline_box
        clipped = clip_segment_to_outline_box(start_xy, end_xy, bounds, clip_margin)
        if clipped is None:
            return None
        start_xy, end_xy = clipped
    seg = pcbnew.PCB_SHAPE(board, pcbnew.SHAPE_T_SEGMENT)
    seg.SetStart(as_point(start_xy[0], start_xy[1], fpoint))
    seg.SetEnd(as_point(end_xy[0], end_xy[1], fpoint))
    seg.SetLayer(pcbnew.F_SilkS)
    seg.SetWidth(int(width if width is not None else max(1, 0.127 * SCALE)))
    board.Add(seg)
    return seg


def add_silk_circle(board, center_xy, radius, fpoint, SCALE, width=None):
    """Add silkscreen circle."""
    circle = pcbnew.PCB_SHAPE(board)
    circle.SetShape(pcbnew.SHAPE_T_CIRCLE)
    circle.SetFilled(False)
    cx, cy = center_xy
    circle.SetStart(as_point(cx, cy, fpoint))
    circle.SetEnd(as_point(cx + radius, cy, fpoint))
    circle.SetCenter(as_point(cx, cy, fpoint))
    circle.SetLayer(pcbnew.F_SilkS)
    circle.SetWidth(int(width if width is not None else max(1, 0.127 * SCALE)))
    board.Add(circle)
    return circle


def add_edge_cuts_circle(board, center_xy, radius, fpoint, SCALE, width=None):
    """Add edge cuts circle."""
    circle = pcbnew.PCB_SHAPE(board)
    circle.SetShape(pcbnew.SHAPE_T_CIRCLE)
    circle.SetFilled(False)
    cx, cy = center_xy
    circle.SetStart(as_point(cx, cy, fpoint))
    circle.SetEnd(as_point(cx + radius, cy, fpoint))
    circle.SetCenter(as_point(cx, cy, fpoint))
    circle.SetLayer(pcbnew.Edge_Cuts)
    circle.SetWidth(int(width if width is not None else max(1, 0.09 * SCALE)))
    board.Add(circle)
    return circle


def add_npth_hole(board, center_xy, radius, index, fpoint, fsize):
    """Add non-plated through hole."""
    fp = pcbnew.FOOTPRINT(board)
    fp.SetReference(f"KMH_{index}")
    fp.SetValue("")
    fp.SetPosition(as_point(0, 0, fpoint))
    if hasattr(fp, "Reference"):
        try:
            fp.Reference().SetVisible(False)
        except Exception:
            pass
    if hasattr(fp, "Value"):
        try:
            fp.Value().SetVisible(False)
        except Exception:
            pass

    pad = pcbnew.PAD(fp)
    dia = int(max(2.0 * radius, 1))
    pad.SetAttribute(pcbnew.PAD_ATTRIB_NPTH)
    pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)
    pad.SetDrillSize(fsize(dia, dia))
    pad.SetSize(fsize(dia, dia))
    pad.SetPosition(as_point(center_xy[0], center_xy[1], fpoint))
    try:
        pad.SetLayerSet(pcbnew.LSET.AllCuMask())
    except Exception:
        pass
    fp.Add(pad)
    board.Add(fp)
    return fp


def add_silk_text(board, text, pos_xy, fpoint, fsize, txt_size, SCALE, size_scale=1.0, align="right"):
    """Add silkscreen text."""
    txt = pcbnew.PCB_TEXT(board)
    txt.SetText(text)
    size = int(max(txt_size * size_scale, 0.4 * SCALE))
    txt.SetTextSize(fsize(size, size))
    txt.SetPosition(as_point(pos_xy[0], pos_xy[1], fpoint))
    if hasattr(txt, "SetHorizJustify"):
        if align == "left":
            txt.SetHorizJustify(pcbnew.GR_TEXT_H_ALIGN_LEFT)
        else:
            txt.SetHorizJustify(pcbnew.GR_TEXT_H_ALIGN_RIGHT)
    txt.SetLayer(pcbnew.F_SilkS)
    board.Add(txt)
    return txt
def add_grouped_segment(board, group, start_xy, end_xy, layer, width, fpoint):
    """Add a segment to the board and optionally to a group."""
    seg = pcbnew.PCB_SHAPE(board, pcbnew.SHAPE_T_SEGMENT)
    seg.SetStart(as_point(start_xy[0], start_xy[1], fpoint))
    seg.SetEnd(as_point(end_xy[0], end_xy[1], fpoint))
    seg.SetLayer(layer)
    seg.SetWidth(int(width))
    board.Add(seg)
    if group is not None:
        group.AddItem(seg)
    return seg


def add_grouped_circle(board, group, center_xy, radius, layer, width, fpoint):
    """Add a circle to the board and optionally to a group."""
    circle = pcbnew.PCB_SHAPE(board)
    circle.SetShape(pcbnew.SHAPE_T_CIRCLE)
    circle.SetFilled(False)
    circle.SetStart(as_point(center_xy[0], center_xy[1], fpoint))
    circle.SetEnd(as_point(center_xy[0] + radius, center_xy[1], fpoint))
    circle.SetCenter(as_point(center_xy[0], center_xy[1], fpoint))
    circle.SetLayer(layer)
    circle.SetWidth(int(width))
    board.Add(circle)
    if group is not None:
        group.AddItem(circle)
    return circle


def get_magnet_aux_layer():
    """Return the auxiliary layer used for magnet keepout helpers."""
    return getattr(pcbnew, 'Dwgs_User', pcbnew.F_SilkS)


def add_grouped_rect_outline(board, group, center_xy, half_w, half_h, angle, layer, width, fpoint):
    """Add a rotated rectangle outline as four grouped segments."""
    tang = (-math.sin(angle), math.cos(angle))
    rad = (math.cos(angle), math.sin(angle))
    pts = []
    for sx, sy in ((-1, -1), (1, -1), (1, 1), (-1, 1)):
        px = center_xy[0] + tang[0] * (sx * half_w) + rad[0] * (sy * half_h)
        py = center_xy[1] + tang[1] * (sx * half_w) + rad[1] * (sy * half_h)
        pts.append((px, py))
    for idx in range(4):
        add_grouped_segment(board, group, pts[idx], pts[(idx + 1) % 4], layer, width, fpoint)
    return pts


def clear_magnet_group(board, magnet_group):
    """Remove all items in an existing magnet group and delete the group."""
    if not magnet_group:
        return None
    try:
        items = list(magnet_group.GetItems())
    except Exception:
        items = []
    for item in items:
        try:
            board.RemoveNative(item)
        except Exception:
            try:
                board.Remove(item)
            except Exception:
                pass
    try:
        magnet_group.RemoveAll()
    except Exception:
        pass
    try:
        board.Remove(magnet_group)
    except Exception:
        pass
    return None


def create_magnet_group(board, name='magnet_pcb'):
    """Create and add a fresh PCB group for magnet helpers."""
    group = pcbnew.PCB_GROUP(board)
    group.SetName(name)
    board.Add(group)
    return group


def add_mounting_hole_fp_at(board, group, center_xy, fp_lib, fp_name, ref, fpoint, net=None):
    """Load a footprint, place it, and optionally attach it to a group."""
    fp = pcbnew.FootprintLoad(fp_lib, fp_name)
    if fp is None:
        return None
    fp.Reference().SetVisible(False)
    fp.Value().SetVisible(False)
    fp.SetReference(ref)
    fp.SetPosition(as_point(center_xy[0], center_xy[1], fpoint))
    if net is not None:
        for pad in fp.Pads():
            pad.SetNet(net)
    board.Add(fp)
    if group is not None:
        group.AddItem(fp)
    return fp

def add_silk_arc_ticks(add_segment, SCALE, radius, angle_start, angle_end, step_deg=1.0, tick_inner=0.8, tick_outer=0.0, major_step=5):
    """Draw degree tick marks along a circular guide."""
    angle = angle_start
    while angle <= angle_end + 1e-9:
        deg = int(round(math.degrees(angle)))
        tick_len = tick_inner * SCALE
        if deg % 10 == 0:
            tick_len *= 3.2
        elif major_step and deg % major_step == 0:
            tick_len *= 2.0
        r0 = radius - tick_len
        r1 = radius + (tick_outer * SCALE)
        p0 = (r0 * math.cos(angle), r0 * math.sin(angle))
        p1 = (r1 * math.cos(angle), r1 * math.sin(angle))
        add_segment(p0, p1)
        angle += math.radians(step_deg)


def add_local_tick_fan(add_segment, SCALE, center_xy, base_angle, fan_deg=18.0, radius_mm=3.0):
    """Draw a local fan of tick marks around a reference point."""
    cx, cy = center_xy
    radius = radius_mm * SCALE
    angle = math.radians(-fan_deg)
    end = math.radians(fan_deg)
    while angle <= end + 1e-9:
        deg = int(round(abs(math.degrees(angle))))
        if deg % 10 == 0:
            tick = 1.2 * SCALE
        elif deg % 5 == 0:
            tick = 0.8 * SCALE
        else:
            tick = 0.45 * SCALE
        local_angle = base_angle + angle
        p0 = (cx + (radius - tick) * math.cos(local_angle), cy + (radius - tick) * math.sin(local_angle))
        p1 = (cx + radius * math.cos(local_angle), cy + radius * math.sin(local_angle))
        add_segment(p0, p1)
        angle += math.radians(1.0)


def iter_outer_mount_points(n_edges, corner_hole_offset, corner_hole_dia, corner_hole_count, outline_corners, n_mh_out, r_mh_out, SCALE):
    """Return outer mounting or corner-alignment points used for silkscreen helpers."""
    if n_edges == 4 and corner_hole_offset > 0:
        corners = outline_corners or []
        if len(corners) >= 4:
            xs = [p[0] for p in corners]
            ys = [p[1] for p in corners]
            max_x = max(xs)
            max_y = max(ys)
            off = float(corner_hole_offset)
            dia = max(float(corner_hole_dia), 0.0)
            d = off / math.sqrt(2.0)
            points = [
                ( max_x - d,  max_y - d, math.radians(45.0), dia),
                (-max_x + d,  max_y - d, math.radians(135.0), dia),
                (-max_x + d, -max_y + d, math.radians(225.0), dia),
                ( max_x - d, -max_y + d, math.radians(315.0), dia),
            ]
            return points[:max(0, min(len(points), int(corner_hole_count)))]
    if n_mh_out <= 0 or r_mh_out <= 0:
        return []
    radius = float(r_mh_out)
    if n_edges > 0:
        radius /= max(math.cos(math.pi / n_edges), 1e-6)
    th0 = 2 * math.pi / n_mh_out
    points = []
    for idx in range(n_mh_out):
        angle = th0 * idx + th0 / 2.0
        points.append((radius * math.cos(angle), radius * math.sin(angle), angle, max(float(corner_hole_dia), 3.2 * SCALE)))
    return points


def add_silk_cross_guides(add_segment, outline_corners, radius):
    """Draw cross and diagonal guide lines."""
    corners = outline_corners or []
    if len(corners) >= 4:
        xs = [p[0] for p in corners]
        ys = [p[1] for p in corners]
        add_segment((min(xs), 0.0), (max(xs), 0.0))
        add_segment((0.0, min(ys)), (0.0, max(ys)))
        add_segment(corners[0], corners[2])
        add_segment(corners[1], corners[3])
        return
    guide_r = radius
    add_segment((-guide_r, 0.0), (guide_r, 0.0))
    add_segment((0.0, -guide_r), (0.0, guide_r))
    diag = guide_r / math.sqrt(2.0)
    add_segment((-diag, -diag), (diag, diag))
    add_segment((-diag, diag), (diag, -diag))


def add_silk_slot_frames(add_segment, n_slots, ri, ro):
    """Draw slot frame guide lines between inner and outer radii."""
    half_slot = math.pi / max(n_slots, 1)
    for idx in range(n_slots):
        a0 = idx * (2 * math.pi / n_slots) - half_slot
        a1 = idx * (2 * math.pi / n_slots) + half_slot
        p00 = (ri * math.cos(a0), ri * math.sin(a0))
        p01 = (ro * math.cos(a0), ro * math.sin(a0))
        p10 = (ri * math.cos(a1), ri * math.sin(a1))
        p11 = (ro * math.cos(a1), ro * math.sin(a1))
        add_segment(p00, p01)
        add_segment(p10, p11)


def iter_corner_points_for_origin(n_edges, corner_hole_offset, corner_hole_dia, corner_hole_count, r_out, origin_xy):
    """Return corner alignment hole points for an offset board origin."""
    if n_edges == 4 and corner_hole_offset > 0:
        max_x = float(r_out)
        max_y = float(r_out)
        off = float(corner_hole_offset)
        dia = max(float(corner_hole_dia), 0.0)
        d = off / math.sqrt(2.0)
        pts = [
            ( origin_xy[0] + max_x - d, origin_xy[1] + max_y - d, math.radians(45.0), dia),
            ( origin_xy[0] - max_x + d, origin_xy[1] + max_y - d, math.radians(135.0), dia),
            ( origin_xy[0] - max_x + d, origin_xy[1] - max_y + d, math.radians(225.0), dia),
            ( origin_xy[0] + max_x - d, origin_xy[1] - max_y + d, math.radians(315.0), dia),
        ]
        return pts[:max(0, min(len(pts), int(corner_hole_count)))]
    return []

# Methods for kicad

