# kmotor_kicad.py
# KiCad renderer only for KMotor_Pro
# Generated during Phase 1 refactoring

import math
import pcbnew


def as_point(x, y, fpoint):
    """Convert coordinates to KiCad point."""
    return fpoint(int(round(x)), int(round(y)))


def item_token(item):
    """Get unique token for KiCad item."""
    for getter in ("GetUuid", "GetKIID"):
        if hasattr(item, getter):
            try:
                kiid = getattr(item, getter)()
                if hasattr(kiid, "AsString"):
                    return kiid.AsString()
                return str(kiid)
            except Exception:
                pass
    if hasattr(item, "m_Uuid"):
        try:
            return item.m_Uuid.AsString()
        except Exception:
            pass
    return str(id(item))


def tag_generated_zone(zone, kind, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
    """Tag zone as generated."""
    priority = GENERATED_ZONE_PRIORITIES[kind]
    try:
        zone.SetAssignedPriority(priority)
    except Exception:
        pass
    zone_name = GENERATED_ZONE_NAME_PREFIX + kind
    for setter in ("SetZoneName", "SetName"):
        if hasattr(zone, setter):
            try:
                getattr(zone, setter)(zone_name)
                break
            except Exception:
                pass
    generated_zone_tokens.add(item_token(zone))


def is_generated_zone(zone, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
    """Check if zone was generated by KMotor."""
    token = item_token(zone)
    if token in generated_zone_tokens:
        return True
    for getter in ("GetZoneName", "GetName"):
        if hasattr(zone, getter):
            try:
                name = getattr(zone, getter)()
                if name and str(name).startswith(GENERATED_ZONE_NAME_PREFIX):
                    return True
            except Exception:
                pass
    if hasattr(zone, "GetAssignedPriority"):
        try:
            return zone.GetAssignedPriority() in GENERATED_ZONE_PRIORITIES.values()
        except Exception:
            pass
    return False


def cleanup_generated_zones(board, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
    """Remove all generated zones from board."""
    zones_to_remove = []
    for zone in board.Zones():
        if is_generated_zone(zone, generated_zone_tokens, GENERATED_ZONE_PRIORITIES, GENERATED_ZONE_NAME_PREFIX):
            zones_to_remove.append(zone)
    for zone in zones_to_remove:
        board.Remove(zone)


def eda_angle(angle, KICAD_VERSION):
    """Convert angle to KiCad EDA format."""
    if KICAD_VERSION < 7:
        return angle * 180 / math.pi * 100
    else:
        return pcbnew.EDA_ANGLE(angle, pcbnew.RADIANS_T)


def add_silk_segment(board, start_xy, end_xy, fpoint, SCALE, width=None, clip_to_outline=False, clip_margin=0.0, bounds=None):
    """Add silkscreen segment."""
    if clip_to_outline and bounds:
        from .kmotor_geometry import clip_segment_to_outline_box
        clipped = clip_segment_to_outline_box(start_xy, end_xy, bounds, clip_margin)
        if clipped is None:
            return None
        start_xy, end_xy = clipped
    seg = pcbnew.PCB_SHAPE(board, pcbnew.SHAPE_T_SEGMENT)
    seg.SetStart(as_point(start_xy[0], start_xy[1], fpoint))
    seg.SetEnd(as_point(end_xy[0], end_xy[1], fpoint))
    seg.SetLayer(pcbnew.F_SilkS)
    seg.SetWidth(int(width if width is not None else max(1, 0.127 * SCALE)))
    board.Add(seg)
    return seg


def add_silk_circle(board, center_xy, radius, fpoint, SCALE, width=None):
    """Add silkscreen circle."""
    circle = pcbnew.PCB_SHAPE(board)
    circle.SetShape(pcbnew.SHAPE_T_CIRCLE)
    circle.SetFilled(False)
    cx, cy = center_xy
    circle.SetStart(as_point(cx, cy, fpoint))
    circle.SetEnd(as_point(cx + radius, cy, fpoint))
    circle.SetCenter(as_point(cx, cy, fpoint))
    circle.SetLayer(pcbnew.F_SilkS)
    circle.SetWidth(int(width if width is not None else max(1, 0.127 * SCALE)))
    board.Add(circle)
    return circle


def add_edge_cuts_circle(board, center_xy, radius, fpoint, SCALE, width=None):
    """Add edge cuts circle."""
    circle = pcbnew.PCB_SHAPE(board)
    circle.SetShape(pcbnew.SHAPE_T_CIRCLE)
    circle.SetFilled(False)
    cx, cy = center_xy
    circle.SetStart(as_point(cx, cy, fpoint))
    circle.SetEnd(as_point(cx + radius, cy, fpoint))
    circle.SetCenter(as_point(cx, cy, fpoint))
    circle.SetLayer(pcbnew.Edge_Cuts)
    circle.SetWidth(int(width if width is not None else max(1, 0.09 * SCALE)))
    board.Add(circle)
    return circle


def add_npth_hole(board, center_xy, radius, index, fpoint, fsize):
    """Add non-plated through hole."""
    fp = pcbnew.FOOTPRINT(board)
    fp.SetReference(f"KMH_{index}")
    fp.SetValue("")
    fp.SetPosition(as_point(0, 0, fpoint))
    if hasattr(fp, "Reference"):
        try:
            fp.Reference().SetVisible(False)
        except Exception:
            pass
    if hasattr(fp, "Value"):
        try:
            fp.Value().SetVisible(False)
        except Exception:
            pass

    pad = pcbnew.PAD(fp)
    dia = int(max(2.0 * radius, 1))
    pad.SetAttribute(pcbnew.PAD_ATTRIB_NPTH)
    pad.SetShape(pcbnew.PAD_SHAPE_CIRCLE)
    pad.SetDrillSize(fsize(dia, dia))
    pad.SetSize(fsize(dia, dia))
    pad.SetPosition(as_point(center_xy[0], center_xy[1], fpoint))
    try:
        pad.SetLayerSet(pcbnew.LSET.AllCuMask())
    except Exception:
        pass
    fp.Add(pad)
    board.Add(fp)
    return fp


def add_silk_text(board, text, pos_xy, fpoint, fsize, txt_size, SCALE, size_scale=1.0, align="right"):
    """Add silkscreen text."""
    txt = pcbnew.PCB_TEXT(board)
    txt.SetText(text)
    size = int(max(txt_size * size_scale, 0.4 * SCALE))
    txt.SetTextSize(fsize(size, size))
    txt.SetPosition(as_point(pos_xy[0], pos_xy[1], fpoint))
    if hasattr(txt, "SetHorizJustify"):
        if align == "left":
            txt.SetHorizJustify(pcbnew.GR_TEXT_H_ALIGN_LEFT)
        else:
            txt.SetHorizJustify(pcbnew.GR_TEXT_H_ALIGN_RIGHT)
    txt.SetLayer(pcbnew.F_SilkS)
    board.Add(txt)
    return txt
